--CREATE A DATABASE WITH MODEL TEMPLATE
CREATE DATABASE BDPrueba; --Crear
ALTER DATABASE BDPrueba MODIFY name = BDTest; --Renombrar
DROP DATABASE BDTest; --Eliminar 

--DB INFO
EXEC sp_helpdb BDPrueba;

--CUSTOMIZING - FILEGROUPS
CREATE DATABASE BDPrueba
ON
(
	NAME = BDPrueba_data,
	FILENAME = 'C:\Data\BDPrueba.mdf',
	SIZE = 10MB, MAXSIZE = 100MB,
	FILEGROWTH = 20%
)
LOG ON
(
	NAME = BDPrueba_log,
	FILENAME = 'C:\Logs\BDPrueba.ldf',
	SIZE = 20MB, MAXSIZE = UNLIMITED,
	FILEGROWTH = 10MB
);

--ADD A FILEGROUP
ALTER DATABASE BDPrueba ADD FILEGROUP BD_FG1;

ALTER DATABASE BDPrueba
ADD FILE
(
	NAME = BDPrueba_F1,
	FILENAME = 'C:\Data\BDPrueba_F1.ndf',
	SIZE = 5MB, MAXSIZE = 100MB,
	FILEGROWTH = 5MB
),
(
	NAME = BDPrueba_F2,
	FILENAME = 'C:\Data\BDPrueba_F2.ndf',
	SIZE = 5MB, MAXSIZE = 100MB,
	FILEGROWTH = 5MB
)
TO FILEGROUP BD_FG1;


USE master;
DROP DATABASE BDPrueba;


